CREATE TABLE TAB_A (ID INT);
CREATE TABLE TAB_B (ID INT);

INSERT INTO TAB_A (ID) VALUES (1),(3),(4),(5),(6);

INSERT INTO TAB_B (id) VALUES
(1),
(2),
(3),
(6),
(7),
(8);

SELECT * FROM TAB_A;
SELECT * FROM TAB_B;

SELECT A.* , B.* FROM TAB_A A INNER JOIN TAB_B B ON A.ID = B.ID;
SELECT A.* , B.* FROM TAB_A A LEFT JOIN TAB_B B ON A.ID = B.ID;
SELECT A.* , B.* FROM TAB_A A RIGHT JOIN TAB_B B ON A.ID = B.ID;
SELECT A.* , B.* FROM TAB_A A FULL JOIN TAB_B B ON A.ID = B.ID;
SELECT A.* , B.* FROM TAB_A A CROSS JOIN TAB_B B;

SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;

UPDATE DEPARTMENTS SET DEPARTMENT_ID = 100 WHERE DEPARTMENT_ID = 10;

SELECT X.EMPLOYEE_ID, X.FIRST_NAME, X.SALARY, X.DEPARTMENT_ID, Y.DEPARTMENT_NAME 
FROM EMPLOYEES X INNER JOIN DEPARTMENTS Y ON X.DEPARTMENT_ID = Y.DEPARTMENT_ID;

SELECT X.EMPLOYEE_ID, X.FIRST_NAME, X.SALARY, X.DEPARTMENT_ID, Y.DEPARTMENT_NAME 
FROM EMPLOYEES X LEFT JOIN DEPARTMENTS Y ON X.DEPARTMENT_ID = Y.DEPARTMENT_ID;

SELECT X.EMPLOYEE_ID, X.FIRST_NAME, X.SALARY, X.DEPARTMENT_ID, Y.DEPARTMENT_NAME 
FROM EMPLOYEES X RIGHT JOIN DEPARTMENTS Y ON X.DEPARTMENT_ID = Y.DEPARTMENT_ID;

SELECT X.EMPLOYEE_ID, X.FIRST_NAME, X.SALARY, X.DEPARTMENT_ID, Y.DEPARTMENT_NAME 
FROM EMPLOYEES X FULL JOIN DEPARTMENTS Y ON X.DEPARTMENT_ID = Y.DEPARTMENT_ID;

SELECT X.EMPLOYEE_ID, X.FIRST_NAME, X.SALARY, X.DEPARTMENT_ID, Y.DEPARTMENT_NAME, C.CITY 
FROM EMPLOYEES X INNER JOIN DEPARTMENTS Y ON X.DEPARTMENT_ID = Y.DEPARTMENT_ID
INNER JOIN LOCATIONS C ON Y.LOCATION_ID = C.LOCATION_ID;

SELECT * FROM EMPLOYEES;

-- Self join to get employee with manager name
SELECT 
    e.employee_id AS emp_id,
    e.first_name AS emp_name,
    m.employee_id AS mgr_id,
    m.first_name AS mgr_name
FROM employees e JOIN employees m ON e.manager_id = m.employee_id
ORDER BY e.employee_id;

-- Create TEAMS table
CREATE OR REPLACE TABLE TEAMS (team_name STRING);

-- Insert values
INSERT INTO TEAMS (team_name) VALUES
('SRH'),
('CHN'),
('RCB'),
('GT');

-- Cross join TEAMS with itself
SELECT 
    t1.team_name AS team1,
    t2.team_name AS team2
FROM TEAMS t1 CROSS JOIN TEAMS t2
WHERE t1.team_name < t2.team_name;