sqlWITH CTE_EMP AS 
(
  SELECT * FROM EMPLOYEES
)
SELECT * FROM CTE_EMP;

 SELECT EMPLOYEE_ID,
      FIRST_NAME,
      SALARY ,
      (SALARY * 10 )/100  AS NEXT_HIKE 
      FROM EMPLOYEES
      WHERE NEXT_HIKE < 500 ;

WITH CTE_SAL AS 
(
   SELECT EMPLOYEE_ID,
      FIRST_NAME,
      SALARY ,
       (SALARY * 10 )/100  AS NEXT_HIKE 
      FROM EMPLOYEES
)
 SELECT *
      FROM CTE_SAL
      WHERE NEXT_HIKE < 500 ;

SELECT EMPLOYEE_ID FROM EMPLOYEES 
      UNION 
SELECT EMPLOYEE_ID FROM DEPENDENTS ;

SELECT EMPLOYEE_ID FROM EMPLOYEES 
      UNION ALL
SELECT EMPLOYEE_ID FROM DEPENDENTS ;

SELECT EMPLOYEE_ID FROM EMPLOYEES 
      INTERSECT
SELECT EMPLOYEE_ID FROM DEPENDENTS ;

SELECT EMPLOYEE_ID FROM EMPLOYEES 
      MINUS
SELECT EMPLOYEE_ID FROM DEPENDENTS ;

WITH CTE_EMP AS 
(
SELECT EMPLOYEE_ID,FIRST_NAME FROM EMPLOYEES 
      UNION 
SELECT EMPLOYEE_ID,FIRST_NAME FROM DEPENDENTS 
)  SELECT * FROM CTE_EMP 
  ORDER BY EMPLOYEE_ID 

WITH CTE_EMP AS 
(
SELECT EMPLOYEE_ID,FIRST_NAME FROM EMPLOYEES 
      UNION 
SELECT EMPLOYEE_ID,RELATIONSHIP FROM DEPENDENTS 
)  SELECT * FROM CTE_EMP 
  ORDER BY EMPLOYEE_ID 

SELECT EMPLOYEE_ID,FIRST_NAME FROM EMPLOYEES 
      UNION 
SELECT EMPLOYEE_ID,LAST_NAME FROM DEPENDENTS 

SELECT EMPLOYEE_ID ,
       SALARY,
       ROW_NUMBER()  OVER(ORDER BY SALARY DESC ) AS RID,
       RANK()  OVER(ORDER BY SALARY DESC ) AS RNK,
       DENSE_RANK()  OVER(ORDER BY SALARY DESC ) AS DRANK,
       LEAD(SALARY) OVER(ORDER BY SALARY DESC) AS NEXT_VAL,
         LAG(SALARY) OVER(ORDER BY SALARY DESC) AS PRE_VAL

       FROM EMPLOYEES 

SELECT * ,
DENSE_RANK()  OVER(ORDER BY SALARY DESC )  AS RNK
FROM EMPLOYEES 
WHERE RNK = 3;

WITH CTE_EMP AS (
    SELECT * ,
    DENSE_RANK()  OVER(ORDER BY SALARY DESC )  AS RNK
    FROM EMPLOYEES 
) SELECT * FROM CTE_EMP WHERE RNK = 3;

WITH CTE_EMP AS (
    SELECT * ,
    DENSE_RANK()  OVER(ORDER BY SALARY DESC )  AS RNK
    FROM EMPLOYEES 
) SELECT * FROM CTE_EMP WHERE RNK = 10;

    SELECT * ,
    DENSE_RANK()  OVER(ORDER BY SALARY DESC )  AS RNK
    FROM EMPLOYEES 
    QUALIFY RNK = 13;

      SELECT * ,
      ROW_NUMBER()  OVER(PARTITION BY DEPARTMENT_ID ORDER BY SALARY DESC )  AS RNK
    FROM EMPLOYEES 
    QUALIFY RNK = 1;